Repository dbl7/rosters, pull requests merged in 2020-05, with the labels that each got.

#3 Add firebase
  .firebaserc
  angular.json
  firebase.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/environments/environment.ts
Labels: enhancement

#4 Add lists and training skeleton
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/list/list-routing.module.ts
  src/app/list/list.module.ts
  src/app/list/list.service.ts
  src/app/list/lists/lists.component.html
  src/app/list/lists/lists.component.scss
  src/app/list/lists/lists.component.spec.ts
  src/app/list/lists/lists.component.ts
  src/app/list/models/list.model.ts
  src/app/training/training.component.html
  src/app/training/training.component.scss
  src/app/training/training.component.spec.ts
  src/app/training/training.component.ts
  src/app/training/training.service.ts
Labels: enhancement

#6 Material theme
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/core/material/app-material.module.ts
  src/app/training/training.component.html
  src/index.html
  src/styles.scss
  src/styles/theme.scss
  src/styles/variables.scss
  tsconfig.json
  tslint.json
Labels: feature

#8 Add page components for routing
  src/app/list/list-routing.module.ts
  src/app/list/list.module.ts
  src/app/list/list.service.ts
  src/app/list/lists/lists.component.html
  src/app/list/models/list.model.ts
  src/app/list/pages/list-page/list-page.component.html
  src/app/list/pages/list-page/list-page.component.scss
  src/app/list/pages/list-page/list-page.component.spec.ts
  src/app/list/pages/list-page/list-page.component.ts
  src/app/list/pages/lists-page/lists-page.component.html
  src/app/list/pages/lists-page/lists-page.component.scss
  src/app/list/pages/lists-page/lists-page.component.spec.ts
  src/app/list/pages/lists-page/lists-page.component.ts
Labels: feature

#9 Login and sign up pages
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/auth/auth-layout/auth-layout.component.html
  src/app/auth/auth-layout/auth-layout.component.scss
  src/app/auth/auth-layout/auth-layout.component.spec.ts
  src/app/auth/auth-layout/auth-layout.component.ts
  src/app/auth/auth-routing.module.ts
  src/app/auth/auth.module.ts
  src/app/auth/auth.service.spec.ts
  src/app/auth/auth.service.ts
  src/app/auth/guards/auth/auth.guard.spec.ts
  src/app/auth/guards/auth/auth.guard.ts
  src/app/auth/models/auth-data.ts
  src/app/auth/models/index.ts
  src/app/auth/pages/login-page/login-page.component.html
  src/app/auth/pages/login-page/login-page.component.scss
  src/app/auth/pages/login-page/login-page.component.spec.ts
  src/app/auth/pages/login-page/login-page.component.ts
  src/app/auth/pages/sign-up-page/sign-up-page.component.html
  src/app/auth/pages/sign-up-page/sign-up-page.component.scss
  src/app/auth/pages/sign-up-page/sign-up-page.component.spec.ts
  src/app/auth/pages/sign-up-page/sign-up-page.component.ts
  src/app/core/core.module.ts
  src/app/core/error-matchers/error-matchers.ts
  src/app/core/material/app-material.module.ts
  src/app/core/services/user/user.service.spec.ts
  src/app/core/services/user/user.service.ts
  src/app/core/validators/validators.ts
  src/app/shared/models/index.ts
  src/app/shared/models/interfaces/user.ts
  src/app/training/training.component.html
  src/app/training/training.component.ts
  tsconfig.json
Labels: feature

#11 feat(training): add the ability to switch list
  angular.json
  src/app/app.component.spec.ts
  src/app/core/services/user/user.service.ts
  src/app/list/list.service.ts
  src/app/list/models/list.model.ts
  src/app/training/components/list-switch/list-switch.component.html
  src/app/training/components/list-switch/list-switch.component.scss
  src/app/training/components/list-switch/list-switch.component.spec.ts
  src/app/training/components/list-switch/list-switch.component.ts
  src/app/training/pages/training-page/training-page.component.html
  src/app/training/pages/training-page/training-page.component.scss
  src/app/training/pages/training-page/training-page.component.ts
  src/app/training/training.module.ts
  src/styles/variables.scss
Labels: feature

#16 fix(tests): get rid of firebase dependencies in components tests
  src/app/auth/pages/login-page/login-page.component.spec.ts
  src/app/auth/pages/sign-up-page/sign-up-page.component.spec.ts
  src/app/list/pages/list-page/list-page.component.spec.ts
Labels: bug
